name: merge-upstream
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # every day at nine

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""

      - name: git merge
        run: |
          git remote add root https://github.com/trustwallet/assets.git
          git fetch root
          git merge root/master -s recursive -X ours
          git push -u origin master
