---
name: Upload on merge

on:
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish the latest token assets

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Sync assets to staging folder
        run: |
          make copy-logos-to-staging
          cp -r dapps staging/dapps
          cp -r exchanges staging/exchanges

      - name: Install Cloudinary CLI
        run: pip3 install --upgrade cloudinary-cli

      - name: Upload assets to Cloudinary
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: |
          cd staging
          cld sync -FK --push assets assets
          cld sync -FK --push dapps dapps
          cld sync -FK --push exchanges exchanges
